export const ARTIFICER = {
  '5e': {
    'Alchemist': {
      flavorText: 'An Alchemist is an expert at combining exotic reagents to produce mystical effects. Alchemists use their creations to give life and to leech it away. Alchemy is the oldest of artificer traditions, and its practitioners\'s diverse means of using their creations to aid in exploration mark them as a category unto themselves.',
      features: [
        { level: 3, name: 'Alchemist Spells', description: 'You always have certain spells prepared after you reach particular levels in this class, as shown in the Alchemist Spells table. These spells count as artificer spells for you, but they don\'t count against the number of artificer spells you prepare: Healing Word and Ray of Sickness (3rd level); Flaming Sphere and Melf\'s Acid Arrow (5th level); Gaseous Form and Mass Healing Word (9th level); Blight and Death Ward (13th level); Cloudkill and Raise Dead (17th level).' },
        { level: 3, name: 'Experimental Elixir', description: 'Whenever you finish a long rest, you can magically produce a number of experimental elixirs in empty flasks — 1 at 3rd level, 2 at 6th, and 3 at 15th. Roll on the Experimental Elixir table for each elixir to determine its effect. As a bonus action, a creature can drink the elixir or administer it to an incapacitated creature. You can create additional elixirs by expending a spell slot of 1st level or higher for each one (rolled randomly or chosen with a higher-level slot).' },
        { level: 5, name: 'Alchemical Savant', description: 'You develop masterful command of magical chemicals, enhancing the healing and harming capabilities of your experimentations. Whenever you cast a spell using your alchemist\'s supplies as the spellcasting focus, you gain a bonus to one roll of the spell: if it restores hit points, add your Intelligence modifier to the roll; if it deals acid, fire, necrotic, or poison damage, add your Intelligence modifier to one damage roll (minimum +1).' },
        { level: 9, name: 'Restorative Reagents', description: 'You can incorporate restorative reagents into some of your works. Whenever a creature drinks an experimental elixir you created, they gain temporary hit points equal to 2d6 + your Intelligence modifier. You can cast lesser restoration without expending a spell slot and without preparing the spell, provided you use alchemist\'s supplies as the spellcasting focus. You can do so a number of times equal to your Intelligence modifier (minimum 1), and you regain all expended uses when you finish a long rest.' },
        { level: 15, name: 'Chemical Mastery', description: 'You have been exposed to so many chemicals that they pose little risk to you, and you can use them to quickly end certain ailments. You gain resistance to acid damage and poison damage, and you\'re immune to the poisoned condition. You can cast greater restoration and heal without expending a spell slot, without preparing the spell, and without providing the material component, provided you use alchemist\'s supplies as the spellcasting focus. Once you cast either spell with this feature, you can\'t cast that spell with it again until you finish a long rest.' },
      ],
    },
    'Armorer': {
      flavorText: 'An Armorer focuses on arcane technology that makes armor into a second skin. An Armorer has mastered the art of wearing heavy armor as if it were a second skin, seamlessly blending physical and magical protection. Armorers push the boundaries of their armor designs, creating highly customized constructs worthy of any workshop.',
      features: [
        { level: 3, name: 'Tools of the Trade', description: 'You gain proficiency with heavy armor. You also gain proficiency with smith\'s tools. If you already have this tool proficiency, you gain proficiency with one other type of artisan\'s tools of your choice.' },
        { level: 3, name: 'Armorer Spells', description: 'You always have certain spells prepared: Magic Missile and Thunderwave (3rd level); Mirror Image and Shatter (5th level); Hypnotic Pattern and Lightning Bolt (9th level); Fire Shield and Greater Invisibility (13th level); Passwall and Wall of Force (17th level).' },
        { level: 3, name: 'Arcane Armor', description: 'Your metallurgical pursuits have led to you becoming adept with suits of armor as arcane conduits. As an action, you can turn a suit of armor you are wearing into Arcane Armor, provided you have smith\'s tools in hand. You gain several benefits: the armor can be donned or doffed as an action; the armor attaches to you and can\'t be removed against your will; if the armor normally has a Strength requirement, the arcane version lacks this requirement; you can use the armor as a spellcasting focus; the armor magically accommodates your anatomy (even if you have extra limbs).' },
        { level: 3, name: 'Armor Model', description: 'Choose a model for your Arcane Armor: Guardian or Infiltrator. The Guardian is a bulky suit that emphasizes defense and strength, granting a Thunder Gauntlets attack (1d8 thunder, marks targets with disadvantage if they don\'t attack you) and a Defensive Field (bonus action to gain temp HP equal to your artificer level). The Infiltrator is a lighter, sleeker suit built for stealth, granting a Lightning Launcher ranged attack (1d6 lightning, ignores cover and once per turn deals +1d6 to a target of your choice) and Powered Steps (+5 ft movement). You can switch models after each long rest.' },
        { level: 5, name: 'Extra Attack', description: 'You can attack twice, instead of once, whenever you take the Attack action on your turn.' },
        { level: 9, name: 'Armor Modifications', description: 'You learn how to use your artificer infusions with your Arcane Armor. The armor now counts as separate items for the purposes of your Infuse Items feature: the armor (including the chest piece), the boots, the helmet, and each gauntlet. Each of those items can bear one infusion; your maximum infused items increases by 2, but those extra items must be part of your Arcane Armor.' },
        { level: 15, name: 'Perfected Armor', description: 'Your Arcane Armor gains additional capabilities depending on the model. Guardian: When a Huge or smaller creature you can see ends its turn within 30 feet of you, you can use your reaction to magically force it to make a Strength saving throw. On a failed save, you pull the creature up to 30 feet directly to an unoccupied space within 5 feet of you, and the creature is knocked prone. Infiltrator: When you hit a creature with your Lightning Launcher, you can deal maximum damage to that target the next time you hit it with the weapon attack during the current turn.' },
      ],
    },
    'Artillerist': {
      flavorText: 'An Artillerist specializes in using magic to hurl energy, projectiles, and explosions on a battlefield. This destructive expert excels at long-range combat. An Artillerist\'s cannons are a marvel of arcane engineering, capable of raining fire on enemies or protecting allies.',
      features: [
        { level: 3, name: 'Tools of the Trade', description: 'You gain proficiency with woodcarver\'s tools. If you already have this tool proficiency, you gain proficiency with one other type of artisan\'s tools of your choice.' },
        { level: 3, name: 'Artillerist Spells', description: 'You always have certain spells prepared: Shield and Thunderwave (3rd level); Scorching Ray and Shatter (5th level); Fireball and Wind Wall (9th level); Ice Storm and Wall of Fire (13th level); Cone of Cold and Wall of Force (17th level).' },
        { level: 3, name: 'Eldritch Cannon', description: 'You\'ve learned how to create a magical cannon. Using woodcarver\'s tools or smith\'s tools (action, 1 minute), you create a Small or Tiny Eldritch Cannon in an unoccupied space within 5 feet. You can have only one cannon at a time. The cannon lasts until the end of your next long rest, until it is reduced to 0 HP, or until you dismiss it. You can have the cannon fire as a bonus action. Choose one of three types: Flamethrower (15-ft cone, 2d8 fire on failed DEX save; ignites unattended flammable objects), Force Ballista (ranged spell attack, 2d8 force + push 5 ft), or Protector (30-ft radius aura, 1d8+INT temporary HP to you or a creature you choose in the area). At 9th level, you can create 2 cannons per rest.' },
        { level: 5, name: 'Arcane Firearm', description: 'You know how to turn a simple weapon into a deadly arcane firearm. At the end of a long rest, you can use woodcarver\'s tools to carve special sigils into a simple or martial weapon or into a wand, staff, or rod. Whenever you cast an artificer spell through that firearm, you can add a +1d8 to one of the spell\'s damage rolls. The benefit lasts until you use this feature again or finish a long rest.' },
        { level: 9, name: 'Explosive Cannon', description: 'Every Eldritch Cannon you create is now more destructive. Its damage rolls all increase by 1d8. As an action, you can command the cannon to detonate if it\'s within 60 feet of you. Doing so destroys the cannon and forces each creature within 20 feet of it to make a DEX saving throw against your spell save DC, taking 3d8 force damage on a failed save or half as much on a successful one.' },
        { level: 15, name: 'Fortified Position', description: 'You\'re a master at forming well-defended emplacements using Eldritch Cannons. You and your allies have half cover while within 10 feet of a cannon you create with Eldritch Cannon, as a result of a shimmering field of magical protection. You can also now have two Eldritch Cannons at a time. You can create two with the same action (but still pay the action cost once), and you can activate both cannons with the same bonus action.' },
      ],
    },
    'Battle Smith': {
      flavorText: 'Armies require protection, and someone has to put things back together if defenses fail. A combination of protector and medic, a Battle Smith is an expert at defending others and at keeping constructs and creatures in good health. Battle Smiths are sought out by any military unit in need of a skilled protector, though they are often freelancers as well.',
      features: [
        { level: 3, name: 'Tools of the Trade', description: 'You gain proficiency with smith\'s tools. If you already have this tool proficiency, you gain proficiency with one other type of artisan\'s tools of your choice.' },
        { level: 3, name: 'Battle Smith Spells', description: 'You always have certain spells prepared: Heroism and Shield (3rd level); Branding Smite and Warding Bond (5th level); Aura of Vitality and Conjure Barrage (9th level); Aura of Purity and Fire Shield (13th level); Banishing Smite and Mass Cure Wounds (17th level).' },
        { level: 3, name: 'Battle Ready', description: 'Your combat training and your experiments with magic have paid off in two ways. First, you gain proficiency with martial weapons. Second, when you attack with a magic weapon, you can use your Intelligence modifier, instead of Strength or Dexterity, for the attack and damage rolls.' },
        { level: 3, name: 'Steel Defender', description: 'Your tinkering has borne you a faithful companion, a steel defender. It is friendly to you and your companions, and it obeys your commands. See its game statistics in the Steel Defender stat block. You determine the creature\'s appearance and construct it. On your turn, you can command the defender to take the Dash, Disengage, Help, or Hide action (no action required). It can make its own attack only if you take the Attack action and forgo one of your own attacks. If it is ever reduced to 0 hit points, it can be rebuilt during a long rest with smith\'s tools.' },
        { level: 5, name: 'Extra Attack', description: 'You can attack twice, instead of once, whenever you take the Attack action on your turn.' },
        { level: 9, name: 'Arcane Jolt', description: 'You\'ve learned new ways to channel arcane energy to harm or heal. When either you hit a target with a magic weapon attack or your steel defender hits a target, you can channel magical energy through the strike to create one of the following effects: The target takes an extra 2d6 force damage. Choose one creature or object you can see within 30 feet of the target. Healing energy flows into the chosen recipient, restoring 2d6 hit points to it. You can use this energy a number of times equal to your Intelligence modifier (minimum 1), but you can do so no more than once on a turn. You regain all expended uses when you finish a long rest.' },
        { level: 15, name: 'Improved Defender', description: 'Your Arcane Jolt and steel defender become more powerful. The extra damage and the healing of your Arcane Jolt both increase to 4d6. Your steel defender gains a +2 bonus to Armor Class. Whenever your steel defender uses its Deflect Attack reaction, the attacker takes force damage equal to 1d4 + your Intelligence modifier.' },
      ],
    },
  },
};
