"""add character narrative fields: backstory, personal_notes, image_path, theme_music_url, character_timeline_events junction, character_npcs junction

Revision ID: 054f0a932e54
Revises: b3c4d5e6f7a8
Create Date: 2026-05-26 22:19:14.781960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '054f0a932e54'
down_revision: Union[str, Sequence[str], None] = 'b3c4d5e6f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_npcs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('npc_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['npc_id'], ['npcs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'npc_id', name='uq_character_npc')
    )
    op.create_index(op.f('ix_character_npcs_character_id'), 'character_npcs', ['character_id'], unique=False)
    op.create_index(op.f('ix_character_npcs_id'), 'character_npcs', ['id'], unique=False)
    op.create_table('character_timeline_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['timeline_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'event_id', name='uq_character_timeline_event')
    )
    op.create_index(op.f('ix_character_timeline_events_character_id'), 'character_timeline_events', ['character_id'], unique=False)
    op.create_index(op.f('ix_character_timeline_events_id'), 'character_timeline_events', ['id'], unique=False)
    op.add_column('characters', sa.Column('backstory', sa.Text(), nullable=True))
    op.add_column('characters', sa.Column('personal_notes', sa.Text(), nullable=True))
    op.add_column('characters', sa.Column('image_path', sa.String(length=500), nullable=True))
    op.add_column('characters', sa.Column('theme_music_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'theme_music_url')
    op.drop_column('characters', 'image_path')
    op.drop_column('characters', 'personal_notes')
    op.drop_column('characters', 'backstory')
    op.drop_index(op.f('ix_character_timeline_events_id'), table_name='character_timeline_events')
    op.drop_index(op.f('ix_character_timeline_events_character_id'), table_name='character_timeline_events')
    op.drop_table('character_timeline_events')
    op.drop_index(op.f('ix_character_npcs_id'), table_name='character_npcs')
    op.drop_index(op.f('ix_character_npcs_character_id'), table_name='character_npcs')
    op.drop_table('character_npcs')
    # ### end Alembic commands ###
