"""add experience_points level_up_pending to characters

Revision ID: 10eb538c7998
Revises: 6d6681c7de9c
Create Date: 2026-05-20 14:18:29.017629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10eb538c7998'
down_revision: Union[str, Sequence[str], None] = '6d6681c7de9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('experience_points', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('characters', sa.Column('level_up_pending', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'level_up_pending')
    op.drop_column('characters', 'experience_points')
    # ### end Alembic commands ###
