"""add session_notes and junction tables

Revision ID: 2e676bacace7
Revises: 4b422f6e0967
Create Date: 2026-05-14 16:13:06.147555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e676bacace7'
down_revision: Union[str, Sequence[str], None] = '4b422f6e0967'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('session_number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('real_world_date', sa.Date(), nullable=True),
    sa.Column('era_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month_order', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('time_of_day', sa.Enum('morning', 'afternoon', 'evening', 'night', 'dawn', name='timeofday'), nullable=True),
    sa.Column('absolute_year', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('gm_notes', sa.Text(), nullable=True),
    sa.Column('music_url', sa.String(length=500), nullable=True),
    sa.Column('is_visible_to_players', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['era_id'], ['calendar_eras.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_notes_campaign_id'), 'session_notes', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_session_notes_id'), 'session_notes', ['id'], unique=False)
    op.create_table('session_note_characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['session_notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'character_id', name='uq_session_note_character')
    )
    op.create_index(op.f('ix_session_note_characters_id'), 'session_note_characters', ['id'], unique=False)
    op.create_index(op.f('ix_session_note_characters_session_id'), 'session_note_characters', ['session_id'], unique=False)
    op.create_table('session_note_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['session_notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'location_id', name='uq_session_note_location')
    )
    op.create_index(op.f('ix_session_note_locations_id'), 'session_note_locations', ['id'], unique=False)
    op.create_index(op.f('ix_session_note_locations_session_id'), 'session_note_locations', ['session_id'], unique=False)
    op.create_table('session_note_npcs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('npc_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['npc_id'], ['npcs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['session_notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'npc_id', name='uq_session_note_npc')
    )
    op.create_index(op.f('ix_session_note_npcs_id'), 'session_note_npcs', ['id'], unique=False)
    op.create_index(op.f('ix_session_note_npcs_session_id'), 'session_note_npcs', ['session_id'], unique=False)
    op.create_table('session_note_timeline_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['timeline_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['session_notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'event_id', name='uq_session_note_timeline_event')
    )
    op.create_index(op.f('ix_session_note_timeline_events_id'), 'session_note_timeline_events', ['id'], unique=False)
    op.create_index(op.f('ix_session_note_timeline_events_session_id'), 'session_note_timeline_events', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_note_timeline_events_session_id'), table_name='session_note_timeline_events')
    op.drop_index(op.f('ix_session_note_timeline_events_id'), table_name='session_note_timeline_events')
    op.drop_table('session_note_timeline_events')
    op.drop_index(op.f('ix_session_note_npcs_session_id'), table_name='session_note_npcs')
    op.drop_index(op.f('ix_session_note_npcs_id'), table_name='session_note_npcs')
    op.drop_table('session_note_npcs')
    op.drop_index(op.f('ix_session_note_locations_session_id'), table_name='session_note_locations')
    op.drop_index(op.f('ix_session_note_locations_id'), table_name='session_note_locations')
    op.drop_table('session_note_locations')
    op.drop_index(op.f('ix_session_note_characters_session_id'), table_name='session_note_characters')
    op.drop_index(op.f('ix_session_note_characters_id'), table_name='session_note_characters')
    op.drop_table('session_note_characters')
    op.drop_index(op.f('ix_session_notes_id'), table_name='session_notes')
    op.drop_index(op.f('ix_session_notes_campaign_id'), table_name='session_notes')
    op.drop_table('session_notes')
    # ### end Alembic commands ###
