"""expand NPC schema - add new fields, relationship tables, rename notes to gm_notes, replace location text with last_known_location_id FK

Revision ID: 2f33714d1275
Revises: c3d8e9f0a2b3
Create Date: 2026-05-05 16:39:48.865242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f33714d1275'
down_revision: Union[str, Sequence[str], None] = 'c3d8e9f0a2b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('npc_player_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('npc_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['npc_id'], ['npcs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('npc_id', 'user_id', 'campaign_id', name='uq_npc_player_relationship')
    )
    op.create_index(op.f('ix_npc_player_relationships_id'), 'npc_player_relationships', ['id'], unique=False)
    op.create_index(op.f('ix_npc_player_relationships_npc_id'), 'npc_player_relationships', ['npc_id'], unique=False)
    op.create_table('npc_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('npc_a_id', sa.Integer(), nullable=False),
    sa.Column('npc_b_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['npc_a_id'], ['npcs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['npc_b_id'], ['npcs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('npc_a_id', 'npc_b_id', name='uq_npc_relationship')
    )
    op.create_index(op.f('ix_npc_relationships_id'), 'npc_relationships', ['id'], unique=False)
    op.create_index(op.f('ix_npc_relationships_npc_a_id'), 'npc_relationships', ['npc_a_id'], unique=False)
    op.execute("CREATE TYPE npcstatus AS ENUM ('alive', 'dead', 'missing', 'unknown')")
    op.add_column('npcs', sa.Column('status', sa.Enum('alive', 'dead', 'missing', 'unknown', name='npcstatus'), nullable=True))
    op.add_column('npcs', sa.Column('age', sa.String(length=100), nullable=True))
    op.add_column('npcs', sa.Column('gender', sa.String(length=100), nullable=True))
    op.add_column('npcs', sa.Column('height', sa.String(length=100), nullable=True))
    op.add_column('npcs', sa.Column('weight', sa.String(length=100), nullable=True))
    op.add_column('npcs', sa.Column('appearance', sa.Text(), nullable=True))
    op.add_column('npcs', sa.Column('image_path', sa.String(length=500), nullable=True))
    op.add_column('npcs', sa.Column('voice', sa.Text(), nullable=True))
    op.add_column('npcs', sa.Column('personality_traits', sa.Text(), nullable=True))
    op.add_column('npcs', sa.Column('ideals', sa.Text(), nullable=True))
    op.add_column('npcs', sa.Column('bonds', sa.Text(), nullable=True))
    op.add_column('npcs', sa.Column('flaws', sa.Text(), nullable=True))
    op.add_column('npcs', sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('npcs', sa.Column('last_known_location_id', sa.Integer(), nullable=True))
    op.add_column('npcs', sa.Column('last_seen_notes', sa.Text(), nullable=True))
    op.add_column('npcs', sa.Column('theme_music_url', sa.String(length=500), nullable=True))
    op.add_column('npcs', sa.Column('gm_notes', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'npcs', 'locations', ['last_known_location_id'], ['id'], ondelete='SET NULL')
    op.drop_column('npcs', 'notes')
    op.drop_column('npcs', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('npcs', sa.Column('location', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('npcs', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'npcs', type_='foreignkey')
    op.drop_column('npcs', 'gm_notes')
    op.drop_column('npcs', 'theme_music_url')
    op.drop_column('npcs', 'last_seen_notes')
    op.drop_column('npcs', 'last_known_location_id')
    op.drop_column('npcs', 'languages')
    op.drop_column('npcs', 'flaws')
    op.drop_column('npcs', 'bonds')
    op.drop_column('npcs', 'ideals')
    op.drop_column('npcs', 'personality_traits')
    op.drop_column('npcs', 'voice')
    op.drop_column('npcs', 'image_path')
    op.drop_column('npcs', 'appearance')
    op.drop_column('npcs', 'weight')
    op.drop_column('npcs', 'height')
    op.drop_column('npcs', 'gender')
    op.drop_column('npcs', 'age')
    op.drop_column('npcs', 'status')
    op.execute("DROP TYPE npcstatus")
    op.drop_index(op.f('ix_npc_relationships_npc_a_id'), table_name='npc_relationships')
    op.drop_index(op.f('ix_npc_relationships_id'), table_name='npc_relationships')
    op.drop_table('npc_relationships')
    op.drop_index(op.f('ix_npc_player_relationships_npc_id'), table_name='npc_player_relationships')
    op.drop_index(op.f('ix_npc_player_relationships_id'), table_name='npc_player_relationships')
    op.drop_table('npc_player_relationships')
    # ### end Alembic commands ###
