"""add gm_notes to timeline_events

Revision ID: 4b422f6e0967
Revises: 7c305440b0c5
Create Date: 2026-05-13 13:02:34.954400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b422f6e0967'
down_revision: Union[str, Sequence[str], None] = '7c305440b0c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeline_events', sa.Column('gm_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timeline_events', 'gm_notes')
    # ### end Alembic commands ###
