"""recreate_character_classes_and_features

Revision ID: 4c427d8464d3
Revises: 9f45eb830743
Create Date: 2026-05-27 15:28:14.475769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c427d8464d3'
down_revision: Union[str, Sequence[str], None] = '9f45eb830743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE character_classes (
            id SERIAL PRIMARY KEY,
            name VARCHAR(100) NOT NULL,
            edition VARCHAR(10) NOT NULL,
            flavor_text TEXT NOT NULL,
            hit_die INTEGER NOT NULL,
            primary_ability VARCHAR(100) NOT NULL,
            spellcasting_ability VARCHAR(50),
            saving_throws JSON NOT NULL,
            armor_proficiencies JSON NOT NULL,
            weapon_proficiencies JSON NOT NULL,
            tool_proficiencies JSON NOT NULL,
            skill_count INTEGER NOT NULL,
            skills_available JSON NOT NULL,
            owner_type ownertype NOT NULL,
            owner_id INTEGER,
            created_at TIMESTAMPTZ DEFAULT now(),
            updated_at TIMESTAMPTZ
        )
    """)
    op.create_index('ix_character_classes_id', 'character_classes', ['id'], unique=False)
    op.create_index('ix_character_classes_name', 'character_classes', ['name'], unique=False)
    op.execute("""
        CREATE TABLE class_features (
            id SERIAL PRIMARY KEY,
            class_id INTEGER NOT NULL REFERENCES character_classes(id) ON DELETE CASCADE,
            level INTEGER NOT NULL,
            feature_name VARCHAR(200) NOT NULL,
            feature_description TEXT NOT NULL,
            created_at TIMESTAMPTZ DEFAULT now()
        )
    """)
    op.create_index('ix_class_features_id', 'class_features', ['id'], unique=False)
    op.create_index('ix_class_features_class_id', 'class_features', ['class_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_class_features_id'), table_name='class_features')
    op.drop_index(op.f('ix_class_features_class_id'), table_name='class_features')
    op.drop_table('class_features')
    op.drop_index(op.f('ix_character_classes_name'), table_name='character_classes')
    op.drop_index(op.f('ix_character_classes_id'), table_name='character_classes')
    op.drop_table('character_classes')
    # ### end Alembic commands ###
