"""remove time_of_day and add end date fields to session_notes

Revision ID: 50a3af85d0e9
Revises: 2e676bacace7
Create Date: 2026-05-18 10:16:14.822333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50a3af85d0e9'
down_revision: Union[str, Sequence[str], None] = '2e676bacace7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_notes', sa.Column('end_year', sa.Integer(), nullable=True))
    op.add_column('session_notes', sa.Column('end_month_order', sa.Integer(), nullable=True))
    op.add_column('session_notes', sa.Column('end_day', sa.Integer(), nullable=True))
    op.drop_column('session_notes', 'time_of_day')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_notes', sa.Column('time_of_day', postgresql.ENUM('morning', 'afternoon', 'evening', 'night', 'dawn', name='timeofday'), autoincrement=False, nullable=True))
    op.drop_column('session_notes', 'end_day')
    op.drop_column('session_notes', 'end_month_order')
    op.drop_column('session_notes', 'end_year')
    # ### end Alembic commands ###
