"""add music_description to session_notes

Revision ID: 639a6a3b3cba
Revises: 50a3af85d0e9
Create Date: 2026-05-18 10:42:05.479928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '639a6a3b3cba'
down_revision: Union[str, Sequence[str], None] = '50a3af85d0e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_notes', sa.Column('music_description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_notes', 'music_description')
    # ### end Alembic commands ###
