"""add use_alignment ability_score_method allow_reroll_ones leveling_type to campaigns

Revision ID: 6d6681c7de9c
Revises: 726b5a82a4df
Create Date: 2026-05-20 14:16:44.577973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d6681c7de9c'
down_revision: Union[str, Sequence[str], None] = '726b5a82a4df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('campaigns', sa.Column('use_alignment', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('campaigns', sa.Column('ability_score_method', sa.String(length=20), nullable=False, server_default='standard_spread'))
    op.add_column('campaigns', sa.Column('allow_reroll_ones', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('campaigns', sa.Column('leveling_type', sa.String(length=20), nullable=False, server_default='milestone'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'leveling_type')
    op.drop_column('campaigns', 'allow_reroll_ones')
    op.drop_column('campaigns', 'ability_score_method')
    op.drop_column('campaigns', 'use_alignment')
    # ### end Alembic commands ###
