"""Add feats table

Revision ID: 70b52bcacf24
Revises: 96d6bc69ecad
Create Date: 2026-03-21 00:20:03.963834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70b52bcacf24'
down_revision: Union[str, Sequence[str], None] = '96d6bc69ecad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('prerequisites', sa.JSON(), nullable=False),
    sa.Column('benefits', sa.JSON(), nullable=False),
    sa.Column('repeatable', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('owner_type', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.CheckConstraint("owner_type IN ('system', 'campaign')", name='feats_owner_type_check')
    )
    op.create_index(op.f('ix_feats_id'), 'feats', ['id'], unique=False)
    op.create_index(op.f('ix_feats_name'), 'feats', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feats_name'), table_name='feats')
    op.drop_index(op.f('ix_feats_id'), table_name='feats')
    op.drop_table('feats')
    # ### end Alembic commands ###
