"""add gm_notes to characters and edition to campaigns

Revision ID: 726b5a82a4df
Revises: a1b2c3d4e5f6
Create Date: 2026-05-19 13:59:13.814223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '726b5a82a4df'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('edition', sa.String(length=10), nullable=True))
    op.execute("UPDATE campaigns SET edition = '5e' WHERE edition IS NULL")
    op.alter_column('campaigns', 'edition', nullable=False)
    op.add_column('characters', sa.Column('gm_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'gm_notes')
    op.drop_column('campaigns', 'edition')
    # ### end Alembic commands ###
