"""add weekdays table and use_weeks/days_per_week to calendar, nullable month name

Revision ID: 7c305440b0c5
Revises: c54f8b027131
Create Date: 2026-05-13 09:59:52.475035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c305440b0c5'
down_revision: Union[str, Sequence[str], None] = 'c54f8b027131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_weekdays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['calendar_id'], ['campaign_calendars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_weekdays_calendar_id'), 'calendar_weekdays', ['calendar_id'], unique=False)
    op.create_index(op.f('ix_calendar_weekdays_id'), 'calendar_weekdays', ['id'], unique=False)
    op.alter_column('calendar_months', 'name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.add_column('campaign_calendars', sa.Column('use_weeks', sa.Boolean(), nullable=False))
    op.add_column('campaign_calendars', sa.Column('days_per_week', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign_calendars', 'days_per_week')
    op.drop_column('campaign_calendars', 'use_weeks')
    op.alter_column('calendar_months', 'name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_index(op.f('ix_calendar_weekdays_id'), table_name='calendar_weekdays')
    op.drop_index(op.f('ix_calendar_weekdays_calendar_id'), table_name='calendar_weekdays')
    op.drop_table('calendar_weekdays')
    # ### end Alembic commands ###
