"""add weapon range_normal and range_long

Revision ID: 94ae0568d367
Revises: 79ca571cc23a
Create Date: 2026-08-21 15:11:30.791461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94ae0568d367'
down_revision: Union[str, Sequence[str], None] = '79ca571cc23a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weapons', sa.Column('range_normal', sa.Integer(), nullable=True))
    op.add_column('weapons', sa.Column('range_long', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weapons', 'range_long')
    op.drop_column('weapons', 'range_normal')
    # ### end Alembic commands ###
