"""Add backgrounds table

Revision ID: 96d6bc69ecad
Revises: e516aa850b34
Create Date: 2026-03-20 19:23:44.894096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96d6bc69ecad'
down_revision: Union[str, Sequence[str], None] = 'e516aa850b34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Check if ownertype enum already exists, if not create it
    connection = op.get_bind()
    result = connection.execute(sa.text(
        "SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ownertype')"
    )).scalar()
    
    if not result:
        # Create the enum if it doesn't exist
        op.execute("CREATE TYPE ownertype AS ENUM ('system', 'campaign')")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backgrounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('skill_proficiencies', sa.JSON(), nullable=False),
    sa.Column('tool_proficiencies', sa.JSON(), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('equipment', sa.JSON(), nullable=False),
    sa.Column('feature', sa.JSON(), nullable=False),
    sa.Column('characteristics', sa.JSON(), nullable=True),
    sa.Column('owner_type', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.CheckConstraint("owner_type IN ('system', 'campaign')", name='backgrounds_owner_type_check')
    )
    op.create_index(op.f('ix_backgrounds_id'), 'backgrounds', ['id'], unique=False)
    op.create_index(op.f('ix_backgrounds_name'), 'backgrounds', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backgrounds_name'), table_name='backgrounds')
    op.drop_index(op.f('ix_backgrounds_id'), table_name='backgrounds')
    op.drop_table('backgrounds')
    # ### end Alembic commands ###
