"""spells_add_higher_level_ritual_concentration_text_components

Revision ID: 9f45eb830743
Revises: 054f0a932e54
Create Date: 2026-05-27 15:21:31.928221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f45eb830743'
down_revision: Union[str, Sequence[str], None] = '054f0a932e54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_class_features_class_id'), table_name='class_features')
    op.drop_index(op.f('ix_class_features_id'), table_name='class_features')
    op.drop_table('class_features')
    op.drop_index(op.f('ix_character_classes_id'), table_name='character_classes')
    op.drop_index(op.f('ix_character_classes_name'), table_name='character_classes')
    op.drop_table('character_classes')
    op.add_column('spells', sa.Column('higher_level', sa.Text(), nullable=True))
    op.add_column('spells', sa.Column('ritual', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('spells', sa.Column('concentration', sa.Boolean(), nullable=False, server_default='false'))
    op.alter_column('spells', 'components',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spells', 'components',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('spells', 'concentration')
    op.drop_column('spells', 'ritual')
    op.drop_column('spells', 'higher_level')
    op.create_table('character_classes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('edition', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('flavor_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('hit_die', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('primary_ability', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('spellcasting_ability', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('saving_throws', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('armor_proficiencies', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('weapon_proficiencies', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('tool_proficiencies', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('skill_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skills_available', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('owner_type', postgresql.ENUM('system', 'campaign', name='ownertype'), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('character_classes_pkey'))
    )
    op.create_index(op.f('ix_character_classes_name'), 'character_classes', ['name'], unique=False)
    op.create_index(op.f('ix_character_classes_id'), 'character_classes', ['id'], unique=False)
    op.create_table('class_features',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('feature_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('feature_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['character_classes.id'], name=op.f('class_features_class_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('class_features_pkey'))
    )
    op.create_index(op.f('ix_class_features_id'), 'class_features', ['id'], unique=False)
    op.create_index(op.f('ix_class_features_class_id'), 'class_features', ['class_id'], unique=False)
    # ### end Alembic commands ###
