"""add locations tables

Revision ID: aab0335f1bb8
Revises: ef08a3336440
Create Date: 2026-04-21 15:05:41.759411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aab0335f1bb8'
down_revision: Union[str, Sequence[str], None] = 'ef08a3336440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('gm_notes', sa.Text(), nullable=True),
    sa.Column('location_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('is_visible_to_players', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_campaign_id'), 'locations', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=False)
    op.create_table('location_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_links_id'), 'location_links', ['id'], unique=False)
    op.create_index(op.f('ix_location_links_location_id'), 'location_links', ['location_id'], unique=False)
    op.create_table('location_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('is_visible_to_players', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_maps_id'), 'location_maps', ['id'], unique=False)
    op.create_index(op.f('ix_location_maps_location_id'), 'location_maps', ['location_id'], unique=False)
    op.create_table('location_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('location_a_id', sa.Integer(), nullable=False),
    sa.Column('location_b_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('direction', sa.Enum('a_above_b', 'b_above_a', 'same_level', name='relationshipdirection'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_a_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_b_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_a_id', 'location_b_id', name='uq_location_relationship')
    )
    op.create_index(op.f('ix_location_relationships_campaign_id'), 'location_relationships', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_location_relationships_id'), 'location_relationships', ['id'], unique=False)
    op.create_table('map_pins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('x_percent', sa.Float(), nullable=False),
    sa.Column('y_percent', sa.Float(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('linked_location_id', sa.Integer(), nullable=True),
    sa.Column('is_visible_to_players', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['linked_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['map_id'], ['location_maps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_map_pins_id'), 'map_pins', ['id'], unique=False)
    op.create_index(op.f('ix_map_pins_map_id'), 'map_pins', ['map_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_map_pins_map_id'), table_name='map_pins')
    op.drop_index(op.f('ix_map_pins_id'), table_name='map_pins')
    op.drop_table('map_pins')
    op.drop_index(op.f('ix_location_relationships_id'), table_name='location_relationships')
    op.drop_index(op.f('ix_location_relationships_campaign_id'), table_name='location_relationships')
    op.drop_table('location_relationships')
    op.drop_index(op.f('ix_location_maps_location_id'), table_name='location_maps')
    op.drop_index(op.f('ix_location_maps_id'), table_name='location_maps')
    op.drop_table('location_maps')
    op.drop_index(op.f('ix_location_links_location_id'), table_name='location_links')
    op.drop_index(op.f('ix_location_links_id'), table_name='location_links')
    op.drop_table('location_links')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_campaign_id'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
