"""add calendar seasons months eras timeline events npc links location links

Revision ID: c54f8b027131
Revises: 2f33714d1275
Create Date: 2026-05-12 15:43:43.036997

NOTE: this migration was originally committed EMPTY — it was autogenerated against a dev
database where the calendar/timeline tables already existed (created by `Base.metadata.create_all`),
so alembic saw no diff. The chain therefore only upgraded cleanly on a database that already had
them; on a fresh database `7c305440b0c5` blew up with `relation "campaign_calendars" does not exist`.
The bodies below are the tables as they stood AT THIS REVISION — later migrations still add
`campaign_calendars.use_weeks`/`days_per_week` (7c305440b0c5), `timeline_events.gm_notes`
(4b422f6e0967) and the `timeline_events.end_*` fields (a1b2c3d4e5f6), so those columns are
deliberately absent here.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c54f8b027131'
down_revision: Union[str, Sequence[str], None] = '2f33714d1275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # campaign_calendars.current_era_id → calendar_eras and calendar_eras.calendar_id →
    # campaign_calendars form a circular FK; the models break it with use_alter=True. Here we
    # create the table without that FK and add it once calendar_eras exists.
    op.create_table('campaign_calendars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('days_per_month', sa.Integer(), nullable=False),
    sa.Column('current_era_id', sa.Integer(), nullable=True),
    sa.Column('current_year', sa.Integer(), nullable=True),
    sa.Column('current_month_order', sa.Integer(), nullable=True),
    sa.Column('current_day', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_calendars_id'), 'campaign_calendars', ['id'], unique=False)
    op.create_index(op.f('ix_campaign_calendars_campaign_id'), 'campaign_calendars', ['campaign_id'], unique=True)

    op.create_table('calendar_seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['calendar_id'], ['campaign_calendars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_seasons_id'), 'calendar_seasons', ['id'], unique=False)
    op.create_index(op.f('ix_calendar_seasons_calendar_id'), 'calendar_seasons', ['calendar_id'], unique=False)

    # `name` is NOT NULL here; 7c305440b0c5 relaxes it to nullable ("Month N" placeholder).
    op.create_table('calendar_months',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['calendar_id'], ['campaign_calendars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['calendar_seasons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_months_id'), 'calendar_months', ['id'], unique=False)
    op.create_index(op.f('ix_calendar_months_calendar_id'), 'calendar_months', ['calendar_id'], unique=False)

    op.create_table('calendar_eras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('abbreviation', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('direction', sa.Enum('ascending', 'descending', name='eradirection'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('epoch_offset', sa.Integer(), nullable=False),
    sa.Column('anchor_era_id', sa.Integer(), nullable=True),
    sa.Column('anchor_era_year', sa.Integer(), nullable=True),
    sa.Column('anchor_this_year', sa.Integer(), nullable=True),
    sa.Column('era_start_absolute', sa.Integer(), nullable=True),
    sa.Column('era_end_absolute', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('is_visible_to_players', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['calendar_id'], ['campaign_calendars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['anchor_era_id'], ['calendar_eras.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_eras_id'), 'calendar_eras', ['id'], unique=False)
    op.create_index(op.f('ix_calendar_eras_calendar_id'), 'calendar_eras', ['calendar_id'], unique=False)

    # Now that calendar_eras exists, close the circular FK.
    op.create_foreign_key(
        'fk_calendar_current_era',
        'campaign_calendars', 'calendar_eras',
        ['current_era_id'], ['id'],
        ondelete='SET NULL',
    )

    # gm_notes (4b422f6e0967) and the end_* span fields (a1b2c3d4e5f6) are added later.
    op.create_table('timeline_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('era_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month_order', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('absolute_year', sa.Integer(), nullable=True),
    sa.Column('is_visible_to_players', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['era_id'], ['calendar_eras.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_events_id'), 'timeline_events', ['id'], unique=False)
    op.create_index(op.f('ix_timeline_events_campaign_id'), 'timeline_events', ['campaign_id'], unique=False)

    op.create_table('timeline_event_npcs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('npc_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['timeline_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['npc_id'], ['npcs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'npc_id', name='uq_timeline_event_npc')
    )
    op.create_index(op.f('ix_timeline_event_npcs_id'), 'timeline_event_npcs', ['id'], unique=False)
    op.create_index(op.f('ix_timeline_event_npcs_event_id'), 'timeline_event_npcs', ['event_id'], unique=False)

    op.create_table('timeline_event_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['timeline_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'location_id', name='uq_timeline_event_location')
    )
    op.create_index(op.f('ix_timeline_event_locations_id'), 'timeline_event_locations', ['id'], unique=False)
    op.create_index(op.f('ix_timeline_event_locations_event_id'), 'timeline_event_locations', ['event_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_timeline_event_locations_event_id'), table_name='timeline_event_locations')
    op.drop_index(op.f('ix_timeline_event_locations_id'), table_name='timeline_event_locations')
    op.drop_table('timeline_event_locations')
    op.drop_index(op.f('ix_timeline_event_npcs_event_id'), table_name='timeline_event_npcs')
    op.drop_index(op.f('ix_timeline_event_npcs_id'), table_name='timeline_event_npcs')
    op.drop_table('timeline_event_npcs')
    op.drop_index(op.f('ix_timeline_events_campaign_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_id'), table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_constraint('fk_calendar_current_era', 'campaign_calendars', type_='foreignkey')
    op.drop_index(op.f('ix_calendar_eras_calendar_id'), table_name='calendar_eras')
    op.drop_index(op.f('ix_calendar_eras_id'), table_name='calendar_eras')
    op.drop_table('calendar_eras')
    op.drop_index(op.f('ix_calendar_months_calendar_id'), table_name='calendar_months')
    op.drop_index(op.f('ix_calendar_months_id'), table_name='calendar_months')
    op.drop_table('calendar_months')
    op.drop_index(op.f('ix_calendar_seasons_calendar_id'), table_name='calendar_seasons')
    op.drop_index(op.f('ix_calendar_seasons_id'), table_name='calendar_seasons')
    op.drop_table('calendar_seasons')
    op.drop_index(op.f('ix_campaign_calendars_campaign_id'), table_name='campaign_calendars')
    op.drop_index(op.f('ix_campaign_calendars_id'), table_name='campaign_calendars')
    op.drop_table('campaign_calendars')
    sa.Enum(name='eradirection').drop(op.get_bind(), checkfirst=True)
