"""add calendar seasons months eras timeline events npc links location links

Revision ID: c54f8b027131
Revises: 2f33714d1275
Create Date: 2026-05-12 15:43:43.036997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c54f8b027131'
down_revision: Union[str, Sequence[str], None] = '2f33714d1275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
