"""Add races table

Revision ID: e516aa850b34
Revises: 
Create Date: 2026-03-18 19:28:48.576163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e516aa850b34'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('adventuring_gear_name_key'), 'adventuring_gear', type_='unique')
    op.drop_index(op.f('idx_adventuring_gear_category'), table_name='adventuring_gear')
    op.drop_index(op.f('idx_adventuring_gear_name'), table_name='adventuring_gear')
    op.create_index(op.f('ix_adventuring_gear_id'), 'adventuring_gear', ['id'], unique=False)
    op.create_index(op.f('ix_adventuring_gear_name'), 'adventuring_gear', ['name'], unique=True)
    op.drop_constraint(op.f('armor_name_key'), 'armor', type_='unique')
    op.drop_index(op.f('idx_armor_name'), table_name='armor')
    op.drop_index(op.f('idx_armor_type'), table_name='armor')
    op.create_index(op.f('ix_armor_id'), 'armor', ['id'], unique=False)
    op.create_index(op.f('ix_armor_name'), 'armor', ['name'], unique=True)
    op.drop_constraint(op.f('creatures_name_key'), 'creatures', type_='unique')
    op.drop_index(op.f('idx_creatures_name'), table_name='creatures')
    op.create_index(op.f('ix_creatures_id'), 'creatures', ['id'], unique=False)
    op.create_index(op.f('ix_creatures_name'), 'creatures', ['name'], unique=True)
    op.drop_constraint(op.f('food_drink_name_key'), 'food_drink', type_='unique')
    op.drop_index(op.f('idx_food_drink_category'), table_name='food_drink')
    op.drop_index(op.f('idx_food_drink_name'), table_name='food_drink')
    op.drop_index(op.f('idx_food_drink_type'), table_name='food_drink')
    op.create_index(op.f('ix_food_drink_id'), 'food_drink', ['id'], unique=False)
    op.create_index(op.f('ix_food_drink_name'), 'food_drink', ['name'], unique=True)
    op.drop_index(op.f('idx_loot_tables_name'), table_name='loot_tables')
    op.drop_index(op.f('idx_loot_tables_owner_id'), table_name='loot_tables')
    op.drop_index(op.f('idx_loot_tables_owner_type'), table_name='loot_tables')
    op.create_index(op.f('ix_loot_tables_id'), 'loot_tables', ['id'], unique=False)
    op.create_index(op.f('ix_loot_tables_name'), 'loot_tables', ['name'], unique=False)
    op.create_index(op.f('ix_loot_tables_owner_id'), 'loot_tables', ['owner_id'], unique=False)
    op.create_index(op.f('ix_loot_tables_owner_type'), 'loot_tables', ['owner_type'], unique=False)
    op.drop_index(op.f('idx_magic_items_name'), table_name='magic_items')
    op.drop_index(op.f('idx_magic_items_rarity'), table_name='magic_items')
    op.drop_index(op.f('idx_magic_items_type'), table_name='magic_items')
    op.drop_constraint(op.f('magic_items_name_key'), 'magic_items', type_='unique')
    op.create_index(op.f('ix_magic_items_id'), 'magic_items', ['id'], unique=False)
    op.create_index(op.f('ix_magic_items_name'), 'magic_items', ['name'], unique=True)
    op.drop_index(op.f('idx_npcs_campaign_id'), table_name='npcs')
    op.drop_index(op.f('idx_npcs_name'), table_name='npcs')
    op.create_index(op.f('ix_npcs_campaign_id'), 'npcs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_npcs_id'), 'npcs', ['id'], unique=False)
    op.create_index(op.f('ix_npcs_name'), 'npcs', ['name'], unique=False)
    op.drop_index(op.f('idx_potions_name'), table_name='potions')
    op.drop_index(op.f('idx_potions_rarity'), table_name='potions')
    op.drop_constraint(op.f('potions_name_key'), 'potions', type_='unique')
    op.create_index(op.f('ix_potions_id'), 'potions', ['id'], unique=False)
    op.create_index(op.f('ix_potions_name'), 'potions', ['name'], unique=True)
    op.drop_index(op.f('idx_spells_level'), table_name='spells')
    op.drop_index(op.f('idx_spells_name'), table_name='spells')
    op.drop_index(op.f('idx_weapons_category'), table_name='weapons')
    op.drop_index(op.f('idx_weapons_name'), table_name='weapons')
    op.drop_constraint(op.f('weapons_name_key'), 'weapons', type_='unique')
    op.create_index(op.f('ix_weapons_id'), 'weapons', ['id'], unique=False)
    op.create_index(op.f('ix_weapons_name'), 'weapons', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weapons_name'), table_name='weapons')
    op.drop_index(op.f('ix_weapons_id'), table_name='weapons')
    op.create_unique_constraint(op.f('weapons_name_key'), 'weapons', ['name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_weapons_name'), 'weapons', ['name'], unique=False)
    op.create_index(op.f('idx_weapons_category'), 'weapons', ['weapon_category'], unique=False)
    op.create_index(op.f('idx_spells_name'), 'spells', ['name'], unique=False)
    op.create_index(op.f('idx_spells_level'), 'spells', ['level'], unique=False)
    op.drop_index(op.f('ix_potions_name'), table_name='potions')
    op.drop_index(op.f('ix_potions_id'), table_name='potions')
    op.create_unique_constraint(op.f('potions_name_key'), 'potions', ['name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_potions_rarity'), 'potions', ['rarity'], unique=False)
    op.create_index(op.f('idx_potions_name'), 'potions', ['name'], unique=False)
    op.drop_index(op.f('ix_npcs_name'), table_name='npcs')
    op.drop_index(op.f('ix_npcs_id'), table_name='npcs')
    op.drop_index(op.f('ix_npcs_campaign_id'), table_name='npcs')
    op.create_index(op.f('idx_npcs_name'), 'npcs', ['name'], unique=False)
    op.create_index(op.f('idx_npcs_campaign_id'), 'npcs', ['campaign_id'], unique=False)
    op.drop_index(op.f('ix_magic_items_name'), table_name='magic_items')
    op.drop_index(op.f('ix_magic_items_id'), table_name='magic_items')
    op.create_unique_constraint(op.f('magic_items_name_key'), 'magic_items', ['name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_magic_items_type'), 'magic_items', ['item_type'], unique=False)
    op.create_index(op.f('idx_magic_items_rarity'), 'magic_items', ['rarity'], unique=False)
    op.create_index(op.f('idx_magic_items_name'), 'magic_items', ['name'], unique=False)
    op.drop_index(op.f('ix_loot_tables_owner_type'), table_name='loot_tables')
    op.drop_index(op.f('ix_loot_tables_owner_id'), table_name='loot_tables')
    op.drop_index(op.f('ix_loot_tables_name'), table_name='loot_tables')
    op.drop_index(op.f('ix_loot_tables_id'), table_name='loot_tables')
    op.create_index(op.f('idx_loot_tables_owner_type'), 'loot_tables', ['owner_type'], unique=False)
    op.create_index(op.f('idx_loot_tables_owner_id'), 'loot_tables', ['owner_id'], unique=False)
    op.create_index(op.f('idx_loot_tables_name'), 'loot_tables', ['name'], unique=False)
    op.drop_index(op.f('ix_food_drink_name'), table_name='food_drink')
    op.drop_index(op.f('ix_food_drink_id'), table_name='food_drink')
    op.create_index(op.f('idx_food_drink_type'), 'food_drink', ['item_type'], unique=False)
    op.create_index(op.f('idx_food_drink_name'), 'food_drink', ['name'], unique=False)
    op.create_index(op.f('idx_food_drink_category'), 'food_drink', ['category'], unique=False)
    op.create_unique_constraint(op.f('food_drink_name_key'), 'food_drink', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_creatures_name'), table_name='creatures')
    op.drop_index(op.f('ix_creatures_id'), table_name='creatures')
    op.create_index(op.f('idx_creatures_name'), 'creatures', ['name'], unique=False)
    op.create_unique_constraint(op.f('creatures_name_key'), 'creatures', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_armor_name'), table_name='armor')
    op.drop_index(op.f('ix_armor_id'), table_name='armor')
    op.create_index(op.f('idx_armor_type'), 'armor', ['armor_type'], unique=False)
    op.create_index(op.f('idx_armor_name'), 'armor', ['name'], unique=False)
    op.create_unique_constraint(op.f('armor_name_key'), 'armor', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_adventuring_gear_name'), table_name='adventuring_gear')
    op.drop_index(op.f('ix_adventuring_gear_id'), table_name='adventuring_gear')
    op.create_index(op.f('idx_adventuring_gear_name'), 'adventuring_gear', ['name'], unique=False)
    op.create_index(op.f('idx_adventuring_gear_category'), 'adventuring_gear', ['category'], unique=False)
    op.create_unique_constraint(op.f('adventuring_gear_name_key'), 'adventuring_gear', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
