"""Initial schema: all tables with owner_type support on encyclopedia

Revision ID: ef08a3336440
Revises: 
Create Date: 2026-04-20 18:18:21.653430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef08a3336440'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adventuring_gear',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('cost', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_type', sa.Enum('system', 'campaign', name='ownertype'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adventuring_gear_id'), 'adventuring_gear', ['id'], unique=False)
    op.create_index(op.f('ix_adventuring_gear_name'), 'adventuring_gear', ['name'], unique=False)
    op.create_table('armor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('armor_type', sa.String(length=50), nullable=False),
    sa.Column('armor_class', sa.Integer(), nullable=False),
    sa.Column('cost', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.String(length=50), nullable=False),
    sa.Column('strength_requirement', sa.Integer(), nullable=True),
    sa.Column('stealth_disadvantage', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_type', sa.Enum('system', 'campaign', name='ownertype'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_armor_id'), 'armor', ['id'], unique=False)
    op.create_index(op.f('ix_armor_name'), 'armor', ['name'], unique=False)
    op.create_table('backgrounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('skill_proficiencies', sa.JSON(), nullable=False),
    sa.Column('tool_proficiencies', sa.JSON(), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('equipment', sa.JSON(), nullable=False),
    sa.Column('feature', sa.JSON(), nullable=False),
    sa.Column('characteristics', sa.JSON(), nullable=True),
    sa.Column('owner_type', sa.Enum('system', 'campaign', name='ownertype'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backgrounds_id'), 'backgrounds', ['id'], unique=False)
    op.create_index(op.f('ix_backgrounds_name'), 'backgrounds', ['name'], unique=False)
    op.create_table('creatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('size', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('alignment', sa.String(length=100), nullable=True),
    sa.Column('challenge_rating', sa.String(length=20), nullable=False),
    sa.Column('armor_class', sa.Integer(), nullable=False),
    sa.Column('hit_points', sa.String(length=100), nullable=False),
    sa.Column('speed', sa.String(length=200), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('dexterity', sa.Integer(), nullable=False),
    sa.Column('constitution', sa.Integer(), nullable=False),
    sa.Column('intelligence', sa.Integer(), nullable=False),
    sa.Column('wisdom', sa.Integer(), nullable=False),
    sa.Column('charisma', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_type', sa.Enum('system', 'campaign', name='ownertype'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creatures_id'), 'creatures', ['id'], unique=False)
    op.create_index(op.f('ix_creatures_name'), 'creatures', ['name'], unique=False)
    op.create_table('feats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('prerequisites', sa.JSON(), nullable=False),
    sa.Column('benefits', sa.JSON(), nullable=False),
    sa.Column('repeatable', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('owner_type', sa.Enum('system', 'campaign', name='ownertype'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feats_id'), 'feats', ['id'], unique=False)
    op.create_index(op.f('ix_feats_name'), 'feats', ['name'], unique=False)
    op.create_table('food_drink',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('cost', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.String(length=100), nullable=True),
    sa.Column('effect', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_type', sa.Enum('system', 'campaign', name='ownertype'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_drink_id'), 'food_drink', ['id'], unique=False)
    op.create_index(op.f('ix_food_drink_name'), 'food_drink', ['name'], unique=False)
    op.create_table('loot_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_type', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('loot_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loot_tables_id'), 'loot_tables', ['id'], unique=False)
    op.create_index(op.f('ix_loot_tables_name'), 'loot_tables', ['name'], unique=False)
    op.create_index(op.f('ix_loot_tables_owner_id'), 'loot_tables', ['owner_id'], unique=False)
    op.create_index(op.f('ix_loot_tables_owner_type'), 'loot_tables', ['owner_type'], unique=False)
    op.create_table('magic_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('item_type', sa.String(length=100), nullable=False),
    sa.Column('rarity', sa.String(length=50), nullable=False),
    sa.Column('attunement_required', sa.Boolean(), nullable=False),
    sa.Column('effect', sa.Text(), nullable=False),
    sa.Column('cost', sa.String(length=50), nullable=True),
    sa.Column('weight', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_type', sa.Enum('system', 'campaign', name='ownertype'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_magic_items_id'), 'magic_items', ['id'], unique=False)
    op.create_index(op.f('ix_magic_items_name'), 'magic_items', ['name'], unique=False)
    op.create_table('potions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('rarity', sa.String(length=50), nullable=False),
    sa.Column('effect', sa.Text(), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('cost', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_type', sa.Enum('system', 'campaign', name='ownertype'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_potions_id'), 'potions', ['id'], unique=False)
    op.create_index(op.f('ix_potions_name'), 'potions', ['name'], unique=False)
    op.create_table('races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ability_score_increases', sa.JSON(), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('traits', sa.JSON(), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('owner_type', sa.Enum('system', 'campaign', name='ownertype'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_races_id'), 'races', ['id'], unique=False)
    op.create_index(op.f('ix_races_name'), 'races', ['name'], unique=False)
    op.create_table('spells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('school', sa.String(length=100), nullable=False),
    sa.Column('casting_time', sa.String(length=100), nullable=False),
    sa.Column('range', sa.String(length=100), nullable=False),
    sa.Column('components', sa.String(length=200), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('classes', sa.String(length=200), nullable=False),
    sa.Column('owner_type', sa.Enum('system', 'campaign', name='ownertype'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spells_id'), 'spells', ['id'], unique=False)
    op.create_index(op.f('ix_spells_name'), 'spells', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('weapons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('weapon_category', sa.String(length=50), nullable=False),
    sa.Column('weapon_type', sa.String(length=50), nullable=False),
    sa.Column('damage', sa.String(length=50), nullable=False),
    sa.Column('damage_type', sa.String(length=50), nullable=False),
    sa.Column('properties', sa.Text(), nullable=True),
    sa.Column('cost', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_type', sa.Enum('system', 'campaign', name='ownertype'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weapons_id'), 'weapons', ['id'], unique=False)
    op.create_index(op.f('ix_weapons_name'), 'weapons', ['name'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_table('campaign_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_members_id'), 'campaign_members', ['id'], unique=False)
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('race', sa.String(), nullable=False),
    sa.Column('char_class', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('background', sa.String(), nullable=True),
    sa.Column('alignment', sa.String(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('dexterity', sa.Integer(), nullable=False),
    sa.Column('constitution', sa.Integer(), nullable=False),
    sa.Column('intelligence', sa.Integer(), nullable=False),
    sa.Column('wisdom', sa.Integer(), nullable=False),
    sa.Column('charisma', sa.Integer(), nullable=False),
    sa.Column('character_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('is_visible_to_players', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_id'), 'characters', ['id'], unique=False)
    op.create_table('npcs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('race', sa.String(length=100), nullable=False),
    sa.Column('occupation', sa.String(length=200), nullable=True),
    sa.Column('alignment', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('backstory', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_visible_to_players', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_npcs_campaign_id'), 'npcs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_npcs_id'), 'npcs', ['id'], unique=False)
    op.create_index(op.f('ix_npcs_name'), 'npcs', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_npcs_name'), table_name='npcs')
    op.drop_index(op.f('ix_npcs_id'), table_name='npcs')
    op.drop_index(op.f('ix_npcs_campaign_id'), table_name='npcs')
    op.drop_table('npcs')
    op.drop_index(op.f('ix_characters_id'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_campaign_members_id'), table_name='campaign_members')
    op.drop_table('campaign_members')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_weapons_name'), table_name='weapons')
    op.drop_index(op.f('ix_weapons_id'), table_name='weapons')
    op.drop_table('weapons')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_spells_name'), table_name='spells')
    op.drop_index(op.f('ix_spells_id'), table_name='spells')
    op.drop_table('spells')
    op.drop_index(op.f('ix_races_name'), table_name='races')
    op.drop_index(op.f('ix_races_id'), table_name='races')
    op.drop_table('races')
    op.drop_index(op.f('ix_potions_name'), table_name='potions')
    op.drop_index(op.f('ix_potions_id'), table_name='potions')
    op.drop_table('potions')
    op.drop_index(op.f('ix_magic_items_name'), table_name='magic_items')
    op.drop_index(op.f('ix_magic_items_id'), table_name='magic_items')
    op.drop_table('magic_items')
    op.drop_index(op.f('ix_loot_tables_owner_type'), table_name='loot_tables')
    op.drop_index(op.f('ix_loot_tables_owner_id'), table_name='loot_tables')
    op.drop_index(op.f('ix_loot_tables_name'), table_name='loot_tables')
    op.drop_index(op.f('ix_loot_tables_id'), table_name='loot_tables')
    op.drop_table('loot_tables')
    op.drop_index(op.f('ix_food_drink_name'), table_name='food_drink')
    op.drop_index(op.f('ix_food_drink_id'), table_name='food_drink')
    op.drop_table('food_drink')
    op.drop_index(op.f('ix_feats_name'), table_name='feats')
    op.drop_index(op.f('ix_feats_id'), table_name='feats')
    op.drop_table('feats')
    op.drop_index(op.f('ix_creatures_name'), table_name='creatures')
    op.drop_index(op.f('ix_creatures_id'), table_name='creatures')
    op.drop_table('creatures')
    op.drop_index(op.f('ix_backgrounds_name'), table_name='backgrounds')
    op.drop_index(op.f('ix_backgrounds_id'), table_name='backgrounds')
    op.drop_table('backgrounds')
    op.drop_index(op.f('ix_armor_name'), table_name='armor')
    op.drop_index(op.f('ix_armor_id'), table_name='armor')
    op.drop_table('armor')
    op.drop_index(op.f('ix_adventuring_gear_name'), table_name='adventuring_gear')
    op.drop_index(op.f('ix_adventuring_gear_id'), table_name='adventuring_gear')
    op.drop_table('adventuring_gear')
    # ### end Alembic commands ###
